name: tainted-love

type: ruby

up:
  - homebrew:
    - openssl
  - ruby: 2.5.3
  - bundler
  - bundler:
      gemfile: example/Gemfile

commands:
  console:
    desc:   'start a console'
    run:    bin/console
  test:
    desc:   'run the tests'
    run:    bin/test

  docs:
    desc:   'generate the documentation'
    run:    bundle exec yard -o docs
